name: zstandard
description: "Flutter plugin to implement Zstandard compression"
version: 1.3.27
homepage: https://landamessenger.com
repository: https://github.com/kdhfred/zstandard

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

flutter:
  plugin:
    platforms:
      android:
        default_package: zstandard_android
      ios:
        default_package: zstandard_ios
      linux:
        default_package: zstandard_linux
      macos:
        default_package: zstandard_macos
      web:
        default_package: zstandard_web
      windows:
        default_package: zstandard_windows

dependencies:
  flutter:
    sdk: flutter
  zstandard_android:
    git:
      url: https://github.com/kdhfred/zstandard.git
      path: zstandard_android
      ref: master
  zstandard_ios:
    git:
      url: https://github.com/kdhfred/zstandard.git
      path: zstandard_ios
      ref: master
  zstandard_linux:
    git:
      url: https://github.com/kdhfred/zstandard.git
      path: zstandard_linux
      ref: master
  zstandard_macos:
    git:
      url: https://github.com/kdhfred/zstandard.git
      path: zstandard_macos
      ref: master
  zstandard_platform_interface:
    git:
      url: https://github.com/kdhfred/zstandard.git
      path: zstandard_platform_interface
      ref: master
  zstandard_web:
    git:
      url: https://github.com/kdhfred/zstandard.git
      path: zstandard_web
      ref: master
  zstandard_windows:
    git:
      url: https://github.com/kdhfred/zstandard.git
      path: zstandard_windows
      ref: master

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  plugin_platform_interface: ^2.1.8
  test: ^1.16.3
